### ISSUE TITLE
Network Tracers

### ISSUE THREAD

**Issue by charga** [jugstalt/gview-gis#19]
It's possible to known a little description of the different types of network tracers that you create? Just to know how to use it. I can use "TraceShortestPath" and works good.

Regards

**Comment by jugstalt** [comment]
There are some network tracers. The main thing is to find the shortest path or the propagation in the network. You can also search for the nearest POI.

However, all of these tracers were developed a long time ago and have never been checked for functionality since then, sorry.

The focus of gView is now to build cartographically attractive maps, which are then published via the gView MapServer as a WMS or AGS GeoServices REST service. 

We use the Map Server as an alternative to ArcGIS Server services for our WebGIS, since the server is more performant than AGS and requires fewer resources.

What do you want to use gView for? If you are looking for a classic desktop GIS system, QGIS might be a better alternative.

Greetings and thanks for your interest in gView

**Comment by charga** [comment]
I'm using gView since gViewOS (4.x) long time ago. The main idea was implement a Network model to maintain from-to topology on an internal development and Tracers (specially Isolation). I began to test oracle as datasource (Spatial, ArcSDE native) and develop some dataconversion tools (Console). I remeber your first iteration with ArcSDE (using wrappers), still works.
Now since last year began to play whith MapServer in order to communicate with via REST. I made my own (using ServiceStack). The new gView 5 provides me all the functionality that I need. The only problem at this time is with Oracle tha has TimeOut problems (OracleManaged) with the multiple Open/Close connections. I'll continue with  the investigation.
Has any advice?
Thanks

**Comment by jugstalt** [comment]
That sounds interesting. If the functionality suits you, I'm satisfied.

So far we only use gView with SQL Server and PostGIS. Oracle is in the product for completeness only and has never actually been tested.

From gView version 4 to 5, the Oracle client changed at some point, the old one contained in the Dotnet Framework was no longer supported.

You may be able to update the Nuget package for the Oracle Managed Client. Unfortunately, we can't help you more here, soffy
