### ISSUE TITLE
Postgres connection not working in Postgre Feature Database Connections.

### ISSUE THREAD

**Issue by arpasuyu** [jugstalt/gview-gis#3]
![image](https://user-images.githubusercontent.com/63927218/87225956-629b9f00-c399-11ea-96c2-7095ccf868a3.png)

Postgres connection not working in Postgre Feature Database Connections but is working under Ogc Postgis as you can see on screen.

**Comment by jugstalt** [comment]
Sorry for my late response, i very busy ;) hope you are still interested in gView GIS.

"Postgre Feature Database" is not the same as "PostGIS". I developed the first versions of gView a long time ago (>20 years). There were no PostGIS and i developed a database format for gView GIS: "Feature Database". This can be used on SQL Server, PostGres and SQLite. Gemetries is stored in BLOBS (not WKB, ...)

So, if you want to view PostGIS use the OGC/PostGIS. 
Since PostGIS (and OGC Databases with WKB, WKT support) exists i recommend to use PostGIS instead of "Feature Database". This format is useful for some usecases and its still in the product for compatibility reasons.
